=== picon/picon-framework/src/picon/core/config.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://piconframework.com/schemas/config" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="piconApplication">
        <xs:complexType>
            <xs:all>
                <xs:element name="settings" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:string" name="homePage" minOccurs="0"/>
                            <xs:element type="xs:string" name="startUp" minOccurs="0"/>
                            <xs:element type="xs:string" name="profile" minOccurs="0"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="profiles" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="profile" minOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:byte" name="showPiconTags" minOccurs="0"/>
                                        <xs:element type="xs:byte" name="cacheMarkup" minOccurs="0"/>
                                        <xs:element type="xs:byte" name="cleanBeforeOutput" minOccurs="0"/>
                                    </xs:sequence>
                                    <xs:attribute type="xs:string" name="name"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="dataSources" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="dataSource" minOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="host" minOccurs="0"/>
                                        <xs:element type="xs:string" name="username" minOccurs="0"/>
                                        <xs:element type="xs:string" name="password" minOccurs="0"/>
                                        <xs:element type="xs:short" name="port" minOccurs="0"/>
                                        <xs:element type="xs:string" name="database" minOccurs="0"/>
                                    </xs:sequence>
                                    <xs:attribute type="xs:string" name="name"/>
                                    <xs:attribute type="xs:string" name="type"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:all>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== picon/picon-framework/trunk/test/config/full.xml
<?xml version="1.0" encoding="UTF-8"?>
<piconApplication xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="http://piconframework.com/schemas/config.xsd">
    <settings>
    <homePage>HomePage</homePage>
    <startUp>auto</startUp>
    <profile>test</profile>
    </settings>
    
    <profiles>
        <profile name="test">
            <showPiconTags>0</showPiconTags>
            <cacheMarkup>1</cacheMarkup>
            </profile>
        </profiles>
        
        <dataSources>
        <dataSource name="testSource" type="MySQL">
            <host>localhost</host>
            <username>someuser</username>
            <password>somepassword</password>
            <port>3306</port>
            <database>somedb</database>
        </dataSource>    
        </dataSources>
</piconApplication>

=== picon/picon-framework/test/config/full.xml
<?xml version="1.0" encoding="UTF-8"?>
<piconApplication xmlns="http://piconframework.com/schemas/config"
                  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xsi:schemaLocation="http://piconframework.com/schemas/config http://piconframework.com/schemas/config.xsd">

    <settings>
        <homePage>HomePage</homePage>
        <startUp>auto</startUp>
        <profile>test</profile>
    </settings>

    <profiles>
        <profile name="test">
            <showPiconTags>0</showPiconTags>
            <cacheMarkup>1</cacheMarkup>
            <cleanBeforeOutput>0</cleanBeforeOutput>
        </profile>
    </profiles>

    <dataSources>
        <dataSource name="testSource" type="MySQL">
            <host>localhost</host>
            <username>someuser</username>
            <password>somepassword</password>
            <port>3306</port>
            <database>somedb</database>
        </dataSource>
    </dataSources>
</piconApplication>
